### PR TITLE
feat #27: support bank module

### PR DESCRIPTION
**Pull request by shibd**
#27

### CODE REVIEW

**Comment by shibd** [comment]
We use the bank module to test our framework, which can show the following results

image

**Comment by RongtongJin** [comment]
Good job! Could you solve the conflict and pass the CI?

**Comment by shibd** [comment]
I'll fix it

**Comment by vongosling** [comment]
What's the bank model? OpenChaos will only support some of the popular distributed systems as the schedule said. If you have some needs in this area, you are welcome to discuss them with us :-)

**Comment by shibd** [comment]
The bank transfer model can easily verify the reliability of the distributed database by checking the total account amount, This will be useful for distributed databases(eg: Tidb) Or distributed transaction framework(eg: Seata)

**Comment by RongtongJin** [comment]
> The bank transfer model can easily verify the reliability of the distributed database by checking the total account amount, This will be useful for distributed databases(eg: Tidb) Or distributed transaction framework(eg: Seata)

In addition to providing models, it would be better to adapt Tidb or Seata or other components suitable for the bank model.

**Pull request closed without merging**
